# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/latest/dbt_project-latest.json
---
name: "tasman_identity_graph"
version: "1.0.0"

config-version: 2
require-dbt-version: [">=1.6.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"

models:
  tasman_identity_graph:
