name: 'tasman_identity_graph'
version: '1.0'

config-version: 2

profile: 'tasman_integration_tests'

seed-paths: ["data"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"

vars:
  tasman_dbt_package:
    identity_events: "{{ ref('identifies_events') }}"

models:
  +materialized: table