# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/latest/dbt_project-latest.json
---
name: "tasman_identity_graph_integration_tests"
version: "0.0.0"

config-version: 2

profile: "tasman_integration_tests"

seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
log-path: "logs"

vars:
  tasman_identity_graph:
    identity_events: "{{ ref('identifies_events') }}"

models:
  +materialized: table
